In [1]:
import numpy as np

### Q.1 Load Data

In [2]:
iris = np.genfromtxt("C:/Users/LENOVO/Desktop/Data Analysis With Python\Iris Project/IRIS.csv",skip_header=1, delimiter=',' ,dtype=float, encoding=None)

In [3]:
iris

array([[5.1, 3.5, 1.4, 0.2, nan, 1. ],
       [4.9, 3. , 1.4, 0.2, nan, 1. ],
       [4.7, 3.2, 1.3, 0.2, nan, 1. ],
       [4.6, 3.1, 1.5, 0.2, nan, 1. ],
       [5. , 3.6, 1.4, 0.2, nan, 1. ],
       [5.4, 3.9, 1.7, 0.4, nan, 1. ],
       [4.6, 3.4, 1.4, 0.3, nan, 1. ],
       [5. , 3.4, 1.5, 0.2, nan, 1. ],
       [4.4, 2.9, 1.4, 0.2, nan, 1. ],
       [4.9, 3.1, 1.5, 0.1, nan, 1. ],
       [5.4, 3.7, 1.5, 0.2, nan, 1. ],
       [4.8, 3.4, 1.6, 0.2, nan, 1. ],
       [4.8, 3. , 1.4, 0.1, nan, 1. ],
       [4.3, 3. , 1.1, 0.1, nan, 1. ],
       [5.8, 4. , 1.2, 0.2, nan, 1. ],
       [5.7, 4.4, 1.5, 0.4, nan, 1. ],
       [5.4, 3.9, 1.3, 0.4, nan, 1. ],
       [5.1, 3.5, 1.4, 0.3, nan, 1. ],
       [5.7, 3.8, 1.7, 0.3, nan, 1. ],
       [5.1, 3.8, 1.5, 0.3, nan, 1. ],
       [5.4, 3.4, 1.7, 0.2, nan, 1. ],
       [5.1, 3.7, 1.5, 0.4, nan, 1. ],
       [4.6, 3.6, 1. , 0.2, nan, 1. ],
       [5.1, 3.3, 1.7, 0.5, nan, 1. ],
       [4.8, 3.4, 1.9, 0.2, nan, 1. ],
       [5. , 3. , 1.6, 0.

### Q.2 Drop Column 4

In [4]:
iris = iris [0:150,[0,1,2,3,5]]
iris

array([[5.1, 3.5, 1.4, 0.2, 1. ],
       [4.9, 3. , 1.4, 0.2, 1. ],
       [4.7, 3.2, 1.3, 0.2, 1. ],
       [4.6, 3.1, 1.5, 0.2, 1. ],
       [5. , 3.6, 1.4, 0.2, 1. ],
       [5.4, 3.9, 1.7, 0.4, 1. ],
       [4.6, 3.4, 1.4, 0.3, 1. ],
       [5. , 3.4, 1.5, 0.2, 1. ],
       [4.4, 2.9, 1.4, 0.2, 1. ],
       [4.9, 3.1, 1.5, 0.1, 1. ],
       [5.4, 3.7, 1.5, 0.2, 1. ],
       [4.8, 3.4, 1.6, 0.2, 1. ],
       [4.8, 3. , 1.4, 0.1, 1. ],
       [4.3, 3. , 1.1, 0.1, 1. ],
       [5.8, 4. , 1.2, 0.2, 1. ],
       [5.7, 4.4, 1.5, 0.4, 1. ],
       [5.4, 3.9, 1.3, 0.4, 1. ],
       [5.1, 3.5, 1.4, 0.3, 1. ],
       [5.7, 3.8, 1.7, 0.3, 1. ],
       [5.1, 3.8, 1.5, 0.3, 1. ],
       [5.4, 3.4, 1.7, 0.2, 1. ],
       [5.1, 3.7, 1.5, 0.4, 1. ],
       [4.6, 3.6, 1. , 0.2, 1. ],
       [5.1, 3.3, 1.7, 0.5, 1. ],
       [4.8, 3.4, 1.9, 0.2, 1. ],
       [5. , 3. , 1.6, 0.2, 1. ],
       [5. , 3.4, 1.6, 0.4, 1. ],
       [5.2, 3.5, 1.5, 0.2, 1. ],
       [5.2, 3.4, 1.4, 0.2, 1. ],
       [4.7, 3

### Q.3 Display Shape, Dimensions and Size

In [5]:
iris.shape

(150, 5)

In [6]:
iris.ndim

2

In [7]:
iris.size

750

### Q.4 Split Data Into 3 Arrays

In [8]:
iris1, iris2, iris3 =np.split(iris,[50,100], axis=0)

In [9]:
iris1

array([[5.1, 3.5, 1.4, 0.2, 1. ],
       [4.9, 3. , 1.4, 0.2, 1. ],
       [4.7, 3.2, 1.3, 0.2, 1. ],
       [4.6, 3.1, 1.5, 0.2, 1. ],
       [5. , 3.6, 1.4, 0.2, 1. ],
       [5.4, 3.9, 1.7, 0.4, 1. ],
       [4.6, 3.4, 1.4, 0.3, 1. ],
       [5. , 3.4, 1.5, 0.2, 1. ],
       [4.4, 2.9, 1.4, 0.2, 1. ],
       [4.9, 3.1, 1.5, 0.1, 1. ],
       [5.4, 3.7, 1.5, 0.2, 1. ],
       [4.8, 3.4, 1.6, 0.2, 1. ],
       [4.8, 3. , 1.4, 0.1, 1. ],
       [4.3, 3. , 1.1, 0.1, 1. ],
       [5.8, 4. , 1.2, 0.2, 1. ],
       [5.7, 4.4, 1.5, 0.4, 1. ],
       [5.4, 3.9, 1.3, 0.4, 1. ],
       [5.1, 3.5, 1.4, 0.3, 1. ],
       [5.7, 3.8, 1.7, 0.3, 1. ],
       [5.1, 3.8, 1.5, 0.3, 1. ],
       [5.4, 3.4, 1.7, 0.2, 1. ],
       [5.1, 3.7, 1.5, 0.4, 1. ],
       [4.6, 3.6, 1. , 0.2, 1. ],
       [5.1, 3.3, 1.7, 0.5, 1. ],
       [4.8, 3.4, 1.9, 0.2, 1. ],
       [5. , 3. , 1.6, 0.2, 1. ],
       [5. , 3.4, 1.6, 0.4, 1. ],
       [5.2, 3.5, 1.5, 0.2, 1. ],
       [5.2, 3.4, 1.4, 0.2, 1. ],
       [4.7, 3

In [10]:
iris2

array([[7. , 3.2, 4.7, 1.4, 2. ],
       [6.4, 3.2, 4.5, 1.5, 2. ],
       [6.9, 3.1, 4.9, 1.5, 2. ],
       [5.5, 2.3, 4. , 1.3, 2. ],
       [6.5, 2.8, 4.6, 1.5, 2. ],
       [5.7, 2.8, 4.5, 1.3, 2. ],
       [6.3, 3.3, 4.7, 1.6, 2. ],
       [4.9, 2.4, 3.3, 1. , 2. ],
       [6.6, 2.9, 4.6, 1.3, 2. ],
       [5.2, 2.7, 3.9, 1.4, 2. ],
       [5. , 2. , 3.5, 1. , 2. ],
       [5.9, 3. , 4.2, 1.5, 2. ],
       [6. , 2.2, 4. , 1. , 2. ],
       [6.1, 2.9, 4.7, 1.4, 2. ],
       [5.6, 2.9, 3.6, 1.3, 2. ],
       [6.7, 3.1, 4.4, 1.4, 2. ],
       [5.6, 3. , 4.5, 1.5, 2. ],
       [5.8, 2.7, 4.1, 1. , 2. ],
       [6.2, 2.2, 4.5, 1.5, 2. ],
       [5.6, 2.5, 3.9, 1.1, 2. ],
       [5.9, 3.2, 4.8, 1.8, 2. ],
       [6.1, 2.8, 4. , 1.3, 2. ],
       [6.3, 2.5, 4.9, 1.5, 2. ],
       [6.1, 2.8, 4.7, 1.2, 2. ],
       [6.4, 2.9, 4.3, 1.3, 2. ],
       [6.6, 3. , 4.4, 1.4, 2. ],
       [6.8, 2.8, 4.8, 1.4, 2. ],
       [6.7, 3. , 5. , 1.7, 2. ],
       [6. , 2.9, 4.5, 1.5, 2. ],
       [5.7, 2

In [11]:
iris3

array([[6.3, 3.3, 6. , 2.5, 3. ],
       [5.8, 2.7, 5.1, 1.9, 3. ],
       [7.1, 3. , 5.9, 2.1, 3. ],
       [6.3, 2.9, 5.6, 1.8, 3. ],
       [6.5, 3. , 5.8, 2.2, 3. ],
       [7.6, 3. , 6.6, 2.1, 3. ],
       [4.9, 2.5, 4.5, 1.7, 3. ],
       [7.3, 2.9, 6.3, 1.8, 3. ],
       [6.7, 2.5, 5.8, 1.8, 3. ],
       [7.2, 3.6, 6.1, 2.5, 3. ],
       [6.5, 3.2, 5.1, 2. , 3. ],
       [6.4, 2.7, 5.3, 1.9, 3. ],
       [6.8, 3. , 5.5, 2.1, 3. ],
       [5.7, 2.5, 5. , 2. , 3. ],
       [5.8, 2.8, 5.1, 2.4, 3. ],
       [6.4, 3.2, 5.3, 2.3, 3. ],
       [6.5, 3. , 5.5, 1.8, 3. ],
       [7.7, 3.8, 6.7, 2.2, 3. ],
       [7.7, 2.6, 6.9, 2.3, 3. ],
       [6. , 2.2, 5. , 1.5, 3. ],
       [6.9, 3.2, 5.7, 2.3, 3. ],
       [5.6, 2.8, 4.9, 2. , 3. ],
       [7.7, 2.8, 6.7, 2. , 3. ],
       [6.3, 2.7, 4.9, 1.8, 3. ],
       [6.7, 3.3, 5.7, 2.1, 3. ],
       [7.2, 3.2, 6. , 1.8, 3. ],
       [6.2, 2.8, 4.8, 1.8, 3. ],
       [6.1, 3. , 4.9, 1.8, 3. ],
       [6.4, 2.8, 5.6, 2.1, 3. ],
       [7.2, 3

### Q.5 Create an Array Header

In [12]:
header = np.array([['sepal length'],['sepal width'],['petal length'],['petal width'],['Species No']])

In [13]:
header

array([['sepal length'],
       ['sepal width'],
       ['petal length'],
       ['petal width'],
       ['Species No']], dtype='<U12')

### Q.6 Descriptive Statistcs

In [14]:
iris_max = iris[:,0:4].max(axis=0)
iris_max

array([7.9, 4.4, 6.9, 2.5])

In [16]:
iris_min = iris[:,0:4].min(axis=0)
iris_min

array([4.3, 2. , 1. , 0.1])

In [17]:
iris_mean = iris[:,0:4].mean(axis=0).round(2)
iris_mean

array([5.84, 3.05, 3.76, 1.2 ])

In [20]:
iris_var = iris[:,0:4].var(axis=0).round(2)
iris_var

array([0.68, 0.19, 3.09, 0.58])

In [21]:
iris_std = iris[:,0:4].std(axis=0).round(2)
iris_std

array([0.83, 0.43, 1.76, 0.76])

### Q.7 Task Solution

In [22]:
iris1_max = iris1[:,0:4].max(axis=0).round(2)
iris1_max

array([5.8, 4.4, 1.9, 0.6])

In [23]:
iris2_max = iris2[:,0:4].max(axis=0).round(2)
iris2_max

array([7. , 3.4, 5.1, 1.8])

In [24]:
iris3_max = iris3[:,0:4].max(axis=0).round(2)
iris3_max

array([7.9, 3.8, 6.9, 2.5])

In [25]:
iris1_min = iris1[:,0:4].min(axis=0).round(2)
iris1_min

array([4.3, 2.3, 1. , 0.1])

In [26]:
iris2_min = iris2[:,0:4].min(axis=0).round(2)
iris2_min

array([4.9, 2. , 3. , 1. ])

In [27]:
iris3_min = iris3[:,0:4].min(axis=0).round(2)
iris3_min

array([4.9, 2.2, 4.5, 1.4])

In [28]:
iris1_mean = iris1[:,0:4].mean(axis=0).round(2)
iris1_mean

array([5.01, 3.42, 1.46, 0.24])

In [29]:
iris2_mean = iris2[:,0:4].mean(axis=0).round(2)
iris2_mean

array([5.94, 2.77, 4.26, 1.33])

In [30]:
iris3_mean = iris3[:,0:4].mean(axis=0).round(2)
iris3_mean

array([6.59, 2.97, 5.55, 2.03])

In [31]:
iris1_var = iris1[:,0:4].var(axis=0).round(2)
iris1_var

array([0.12, 0.14, 0.03, 0.01])

In [32]:
iris2_var = iris2[:,0:4].var(axis=0).round(2)
iris2_var

array([0.26, 0.1 , 0.22, 0.04])

In [33]:
iris3_var = iris3[:,0:4].var(axis=0).round(2)
iris3_var

array([0.4 , 0.1 , 0.3 , 0.07])

In [34]:
iris1_std = iris1[:,0:4].std(axis=0).round(2)
iris1_std

array([0.35, 0.38, 0.17, 0.11])

In [35]:
iris2_std = iris2[:,0:4].std(axis=0).round(2)
iris2_std

array([0.51, 0.31, 0.47, 0.2 ])

In [36]:
iris3_std = iris3[:,0:4].std(axis=0).round(2)
iris3_std

array([0.63, 0.32, 0.55, 0.27])

### Q.8 Task Solution

In [37]:
iris1_mean[1] > iris2_mean[1]

True

### Q.9 Task Solution

In [38]:
iris1_mean[2] > iris3_mean[2]

False

### Q.10 Save The Arrays


In [41]:
np.savetxt("C:/Users/LENOVO/Desktop/Data Analysis With Python/Iris.txt",( iris_max,iris_mean,iris_min),fmt='%s',delimiter=',')